spring:
  datasource:
    password: ?Dust7498?
    url: jdbc:mysql://localhost:3306/servermanager
    username: root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
        format_sql: true
    show-sql: true